import type { NextPage } from 'next';
import Head from 'next/head';
import { useSession, signIn, signOut } from 'next-auth/react';

const Main: NextPage = () => {
  const { data: session } = useSession();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center">
        <h1>Hello World</h1>
        {session ? 'Logged in' : <button onClick={() => signIn()}>Log In</button>}
      </main>
    </div>
  );
};

export default Main;
