import type { NextPage } from 'next';
import Head from 'next/head';
import { useSession, signIn, signOut } from 'next-auth/react';

const Main: NextPage = () => {
  const { data: session, status } = useSession();

  if (status === 'loading') {
    return <div>Loading...</div>;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center">
        <h1>Hello World</h1>
        {session ? (
          <div>
            <p>Logged in as {session?.user.username} </p>
            <button onClick={() => signOut()}>Log Out</button>
          </div>
        ) : (
          <button onClick={() => signIn()}>Log In</button>
        )}
      </main>
    </div>
  );
};

export default Main;
